#!/usr/bin/env bash
# Creates PID file, displays messages indefinitely, and handles signals

# 1. Yazildiyi an öz PID nomremizi fayla qeyd edir
echo "$$" > /tmp/myscript.pid

# 2. Siqnallari sertde teleb olunan mesajlarla havada tutur
trap "echo "Y U no love me?!"" SIGINT
trap "echo "I hate the kill command"; rm -f /tmp/myscript.pid; exit 0" SIGTERM
trap "rm -f /tmp/myscript.pid; exit 0" SIGQUIT

# 3. Sonsuz dovr
while true; do
    echo "To infinity and beyond"
    sleep 2
done
